### PR TITLE
Update droplet-actions.service.ts

### PR DESCRIPTION
**Pull request by Serdnaley**
Fix resize actions for droplet

### CODE REVIEW

**Comment by johnbwoodruff** [comment]
Copy-paste fail! 😅 Thanks for catching that, I appreciate the contribution!

**Comment by Serdnaley** [comment]
Always welcome 😌 And thanks for quick reply

**Comment by Serdnaley** [comment]
This library is very helpful! If not for you, I would now spend a couple of hours writing the methods I need... Thanks for saving me time 😄

**Review by johnbwoodruff — APPROVED** [review]

**Comment by johnbwoodruff** [comment]
@Serdnaley so glad it's useful to you!

I just published v2.0.2 to npm, thanks again!

**Pull request merged**
